BIN = test
CC = clang

# debug mode
G = -g
FLAGS = -DAPPLE -Wall -pedantic -mmacosx-version-min=10.5 -arch x86_64 \
-fmessage-length=0 -UGLFW_CDECL -fprofile-arcs -ftest-coverage

INC = -I ../common/include -I/sw/include -I/usr/local/include -I./include
L = ../common/osx/
LOC_LIB = $(L)libglfw3.a
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit \
-framework CoreVideo
SRC = main.c gl3w.c

all:
	${CC} ${FLAGS} ${FRAMEWORKS} -o ${BIN} ${SRC} ${G} ${INC} ${LOC_LIB}

