BIN = cubemap
CC = g++
FLAGS = -Wall -pedantic
INC = -I ../common/include
LOC_LIB = ../common/lin32/libGLEW.a ../common/lin32/libglfw3.a
SYS_LIB = -lGL -lX11 -lXxf86vm -lXrandr -lpthread -lXi -ldl -lrt -lstdc++ \
-lXinerama -lXcursor
SRC = main.cpp maths_funcs.cpp gl_utils.cpp stb_image.c obj_parser.cpp

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}

