BIN = raytracer.exe
CC = g++
FLAGS = -Wall -pedantic -m64 -DGLEW_STATIC
INC = -I ../common/include
LOC_LIB = ../common/src/GL/glew.c ../common/win64_gcc/libglfw3dll.a
SYS_LIB = -lOpenGL32 -L ./ -lglfw3 -lm
SRC = main.c gl_utils.cpp maths_funcs.cpp stb_image_write.c

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}

