BIN = vrdemo
CC = gcc
FLAGS = -Wall -pedantic -m64 -g -std=c99
I = -I ../common/include -I src/
L = ../common/lin64
STA_LIBS = ${L}/libGLEW.a ${L}/libglfw3.a
DYN_LIBS = -lGL -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lXinerama -lXcursor \
-ldl -lrt -lm
SRC = src/main.c src/camera.c src/mesh.c src/text.c

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${I} ${STA_LIBS} ${DYN_LIBS}
