BIN = vulkanhw.exe
CC = gcc
FLAGS = -Wall -pedantic -std=c99
INC = -I ../common/include
LOC_LIB = ../common/win32/glfw3dll.a
SYS_LIB = -L ./ -lglfw3 -lm
SRC = main.c

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}
