BIN = test
CC = clang++
FLAGS = -Wall -pedantic -fmessage-length=78 -m64
I = -I ../common/include
L = ../common/lin64
STAL = ${L}/libGLEW.a ${L}/libglfw3.a
DYNL = -lGL -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lXinerama -lXcursor \
-ldl -lrt -lm
SRC = main.c obj_parser.cpp

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${I} ${STAL} ${DYNL}
