BIN = cubemap
CC = g++
FLAGS = -Wall -pedantic
INC = -I ../common/include
LOC_LIB = ../common/lin64/libGLEW.a ../common/lin64/libglfw3.a
DYN_LIBS = -lGL -lX11 -lXxf86vm -lXrandr -lpthread -lXi -lXinerama -lXcursor \
-ldl -lrt -lm -L${L} -lIrrKlang -lSDL2 -lstdc++
SRC = main.cpp maths_funcs.cpp gl_utils.cpp stb_image.c obj_parser.cpp

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${DYN_LIBS}

